spring.data.mongodb.uri=mongodb+srv://gabo0103_db_user:pnC5PilxtvEulhF9@cluster0.soosrgl.mongodb.net/fitplan?retryWrites=true&w=majority

server.port=8081

spring.application.name=FitPlan Backend

spring.data.mongodb.auto-index-creation=true